In [5]:
import pandas as pd
from src.recsys_baseline import VSKNN_STAN
from src.evaluation import evaluate_sessions, MRR, HitRate
from src.utils import evaluation_results_to_csv

# Item knn sesion based recommendation
This is the base model that will be used to compare the RL model with.

# Initialise the model (`VSKNN_STAN`)
Model parameters are based on research of [S. Latifi, N. Mauro and D. Jannach. 2021. Session-aware recommendation: a surprising quest for the state-of-the-art. Information Sciences](https://doi.org/10.1016/j.ins.2021.05.048) 

* Optimised parameters for Diginetica dataset: [config](https://github.com/rn5l/session-rec/blob/5dcd583cbd8d44703a5248b9a308945f24b91390/conf/save/diginetica/window/window_multiple_digi_vstan.yml)  
    k: 100  
    sample_size: 1000  
    similarity: 'vec'  
    stan:  
    lambda_spw: 4.9  
    lambda_snh: 80  
    lambda_inh: 9.8  
    vsknn:  
    lambda_ipw: 4.9  
    lambda_idf: 5  


* Optimised parameters for Retail Rocket dataset: [config](https://github.com/rn5l/session-rec/blob/5dcd583cbd8d44703a5248b9a308945f24b91390/conf/save/retailrocket/session_based/window/window_retailr_vstan.yml)  
    k: 500  
    sample_size: 1000  
    similarity: 'cosine'  
    stan:  
    lambda_spw: 7.24  
    lambda_snh: 100  
    lambda_inh: 3.62  
    vsknn:  
    lambda_ipw: 3.62  
    lambda_idf: 1

## Diginetica

In [6]:
train_data = pd.read_csv(r'data\processed datasets\diginetica\interactions_train_tr.txt',
                    sep='\t',)
display(train_data.head())
display(train_data.shape)

,Type,SessionId,ItemId,Time,Date,Datestamp,TimeO,ItemSupport
0,view,1,9654,1.462752e+09,2016-05-09,1.462752e+09,2016-05-09 00:01:15.848000+00:00,74
1,view,1,33043,1.462752e+09,2016-05-09,1.462752e+09,2016-05-09 00:02:53.912000+00:00,41
2,view,1,32118,1.462752e+09,2016-05-09,1.462752e+09,2016-05-09 00:04:03.569000+00:00,19
3,view,1,12352,1.462752e+09,2016-05-09,1.462752e+09,2016-05-09 00:05:29.870000+00:00,79
4,view,1,35077,1.462752e+09,2016-05-09,1.462752e+09,2016-05-09 00:06:30.072000+00:00,47

(102272, 8)

In [7]:
test_data = pd.read_csv(r'data\processed datasets\diginetica\interactions_test.txt',
                    sep='\t',)

display(test_data.head())
display(test_data.shape)

,Type,SessionId,ItemId,Time,Date,Datestamp,TimeO,ItemSupport
0,view,289,125013,1.464221e+09,2016-05-26,1.464221e+09,2016-05-26 00:00:18.301000+00:00,7
1,view,289,64068,1.464222e+09,2016-05-26,1.464221e+09,2016-05-26 00:14:07.735000+00:00,6
2,view,289,133346,1.464222e+09,2016-05-26,1.464221e+09,2016-05-26 00:14:38.934000+00:00,6
3,view,289,198930,1.464222e+09,2016-05-26,1.464221e+09,2016-05-26 00:18:48.607000+00:00,7
4,view,302,36202,1.464221e+09,2016-05-26,1.464221e+09,2016-05-26 00:00:45.583000+00:00,23

(64761, 8)

In [8]:
model_Digi = VSKNN_STAN(k=100,
                     sample_size=1000,
                     similarity='vec',
                    #    stan:  
                     lambda_spw=4.9,  
                     lambda_snh=80,  
                     lambda_inh=9.8,  
                    #    vsknn:  
                     lambda_ipw=4.9, 
                     lambda_idf=5
                       )

In [9]:
model_Digi.fit(train=train_data, test=test_data)

In [10]:
metrics = [
    MRR(2),
    MRR(3),
    MRR(4),
    MRR(5),
    MRR(10),
    MRR(15),
    MRR(20),
    HitRate(1),
    HitRate(2),
    HitRate(3),
    HitRate(4),
    HitRate(5),
    HitRate(10),
    HitRate(15),
    HitRate(20)]

output = evaluate_sessions(pr=model_Digi,
                  metrics= metrics,
                  test_data=test_data,
                  train_data=train_data,
                  cut_off=20)
evaluation_results_to_csv(output=output, dataset_name='Diginetica', algo_name='VSTAN (Baseline)', reward_func='no reward func')

START evaluation of  64761  actions in  14163  sessions
    eval process:  0  of  64761  actions:  0.0  %
    eval process:  1000  of  64761  actions:  1.5441392195920385  %
    eval process:  2000  of  64761  actions:  3.088278439184077  %
    eval process:  3000  of  64761  actions:  4.632417658776116  %
    eval process:  4000  of  64761  actions:  6.176556878368154  %
    eval process:  5000  of  64761  actions:  7.720696097960192  %
    eval process:  6000  of  64761  actions:  9.264835317552231  %
    eval process:  7000  of  64761  actions:  10.808974537144268  %
    eval process:  8000  of  64761  actions:  12.353113756736308  %
    eval process:  9000  of  64761  actions:  13.897252976328344  %
    eval process:  10000  of  64761  actions:  15.441392195920384  %
    eval process:  11000  of  64761  actions:  16.985531415512423  %
    eval process:  12000  of  64761  actions:  18.529670635104463  %
    eval process:  13000  of  64761  actions:  20.0738098546965  %
    eval process:  14000  of  64761  actions:  21.617949074288536  %
    eval process:  15000  of  64761  actions:  23.162088293880576  %
    eval process:  16000  of  64761  actions:  24.706227513472616  %
    eval process:  17000  of  64761  actions:  26.250366733064652  %
    eval process:  18000  of  64761  actions:  27.79450595265669  %
    eval process:  19000  of  64761  actions:  29.33864517224873  %
    eval process:  20000  of  64761  actions:  30.88278439184077  %
    eval process:  21000  of  64761  actions:  32.426923611432805  %
    eval process:  22000  of  64761  actions:  33.971062831024845  %
    eval process:  23000  of  64761  actions:  35.515202050616885  %
    eval process:  24000  of  64761  actions:  37.059341270208925  %
    eval process:  25000  of  64761  actions:  38.603480489800965  %
    eval process:  26000  of  64761  actions:  40.147619709393  %
    eval process:  27000  of  64761  actions:  41.69175892898504  %
    eval process:  28000  of  64761  actions:  43.23589814857707  %
    eval process:  29000  of  64761  actions:  44.78003736816911  %
    eval process:  30000  of  64761  actions:  46.32417658776115  %
    eval process:  31000  of  64761  actions:  47.86831580735319  %
    eval process:  32000  of  64761  actions:  49.41245502694523  %
    eval process:  33000  of  64761  actions:  50.956594246537264  %
    eval process:  34000  of  64761  actions:  52.500733466129304  %
    eval process:  35000  of  64761  actions:  54.044872685721344  %
    eval process:  36000  of  64761  actions:  55.58901190531338  %
    eval process:  37000  of  64761  actions:  57.133151124905424  %
    eval process:  38000  of  64761  actions:  58.67729034449746  %
    eval process:  39000  of  64761  actions:  60.221429564089505  %
    eval process:  40000  of  64761  actions:  61.76556878368154  %
    eval process:  41000  of  64761  actions:  63.30970800327358  %
    eval process:  42000  of  64761  actions:  64.85384722286561  %
    eval process:  43000  of  64761  actions:  66.39798644245765  %
    eval process:  44000  of  64761  actions:  67.94212566204969  %
    eval process:  45000  of  64761  actions:  69.48626488164173  %
    eval process:  46000  of  64761  actions:  71.03040410123377  %
    eval process:  47000  of  64761  actions:  72.5745433208258  %
    eval process:  48000  of  64761  actions:  74.11868254041785  %
    eval process:  49000  of  64761  actions:  75.66282176000988  %
    eval process:  50000  of  64761  actions:  77.20696097960193  %
    eval process:  51000  of  64761  actions:  78.75110019919396  %
    eval process:  52000  of  64761  actions:  80.295239418786  %
    eval process:  53000  of  64761  actions:  81.83937863837804  %
    eval process:  54000  of  64761  actions:  83.38351785797008  %
    eval process:  55000  of  64761  actions:  84.92765707756212  %
    eval process:  56000  of  64761  actions:  86.47179629715414  %
    eval process:  57000  of  64761  actions:  88.0159355167462  %
    eval process:  58000  of  64761  actions:  89.56007473633822  %
    eval process:  59000  of  64761  actions:  91.10421395593026  %
    eval process:  60000  of  64761  actions:  92.6483531755223  %
    eval process:  61000  of  64761  actions:  94.19249239511434  %
    eval process:  62000  of  64761  actions:  95.73663161470638  %
    eval process:  63000  of  64761  actions:  97.28077083429842  %
    eval process:  64000  of  64761  actions:  98.82491005389046  %
END evaluation

       Dataset         Algorithm Reward Function        Metric     Value
0   Diginetica  VSTAN (Baseline)  no reward func       MRR@2:   0.144176
1   Diginetica  VSTAN (Baseline)  no reward func       MRR@3:   0.159565
2   Diginetica  VSTAN (Baseline)  no reward func       MRR@4:   0.168548
3   Diginetica  VSTAN (Baseline)  no reward func       MRR@5:   0.174540
4   Diginetica  VSTAN (Baseline)  no reward func      MRR@10:   0.187495
5   Diginetica  VSTAN (Baseline)  no reward func      MRR@15:   0.192192
6   Diginetica  VSTAN (Baseline)  no reward func      MRR@20:   0.194401
7   Diginetica  VSTAN (Baseline)  no reward func   HitRate@1:   0.109431
8   Diginetica  VSTAN (Baseline)  no reward func   HitRate@2:   0.178920
9   Diginetica  VSTAN (Baseline)  no reward func   HitRate@3:   0.225088
10  Diginetica  VSTAN (Baseline)  no reward func   HitRate@4:   0.261018
11  Diginetica  VSTAN (Baseline)  no reward func   HitRate@5:   0.290980
12  Diginetica  VSTAN (Baseline)  no reward func  HitRate@10:   0.387920
13  Diginetica  VSTAN (Baseline)  no reward func  HitRate@15:   0.447290
14  Diginetica  VSTAN (Baseline)  no reward func  HitRate@20:   0.486719

## Retail Rocket

In [ ]:
train_data = pd.read_csv(r'data\processed datasets\retailrocket\events_train - Filtered items with min 30 actions.csv',
                    sep='\t',)
display(train_data.head())
display(train_data.shape)

In [ ]:
test_data = pd.read_csv(r'data\processed datasets\retailrocket\events_test - Filtered items with min 30 actions.csv',
                    sep='\t',)

display(test_data.head())
display(test_data.shape)

In [ ]:
model_Ret = VSKNN_STAN(k=500,
                       sample_size=1000,
                       similarity='cosine',  
                       #stan:  
                       lambda_spw=7.24,  
                       lambda_snh=100,  
                       lambda_inh=3.62,  
                       #vsknn:  
                       lambda_ipw=3.62, 
                       lambda_idf=1
                       )

In [ ]:
model_Ret.fit(train=train_data, test=test_data)

In [ ]:
metrics = [
    MRR(2),
    MRR(3),
    MRR(4),
    MRR(5),
    MRR(10),
    MRR(15),
    MRR(20),
    HitRate(1),
    HitRate(2),
    HitRate(3),
    HitRate(4),
    HitRate(5),
    HitRate(10),
    HitRate(15),
    HitRate(20)]

output = evaluate_sessions(pr=model_Ret,
                  metrics= metrics,
                  test_data=test_data,
                  train_data=train_data,
                  cut_off=20)
evaluation_results_to_csv(output=output, dataset_name='Retailrocket', algo_name='VSTAN (Baseline)', reward_func='no reward func')